### Register User
POST http://localhost:8000/auth/create
Content-Type: application/json

{
    "name":"Carlos",
    "last_name":"Carlos",
    "email":"carlos12@gmail.com",
    "password":"123456789"
}

### Login User
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email":"carlos1@gmail.com",
    "password":"123456789"
}

### Update User
PUT http://localhost:8000/auth/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQ2FybG9zIiwibGFzdF9uYW1lIjoiQ2FybG9zIiwiZW1haWwiOiJjYXJsb3MxNkBnbWFpbC5jb20iLCJpZCI6MTAsImNyZWF0ZWRfYXQiOiIyMDIwLTEwLTI2VDAwOjEwOjM3LjAwMFoiLCJ1cGRhdGVfYXQiOiIyMDIwLTEwLTI2VDAwOjEwOjM3LjAwMFoiLCJpYXQiOjE2MDM2NzEwMzcsImV4cCI6MTYwMzY3NDYzN30.J5uM2pnd0kUMjZ9UbuZKM0jRB_GdDEEGQKpD_-JFoXM

{
    "name":"newName",
    "last_name":"newName",
    "email":"newEmailssss@gmail.com",
    "password":"newPass123456"
}
